[program:queue-worker]
command=php /var/www/html/artisan queue:work --queue=notifications,default --sleep=3 --tries=3 --timeout=90 --max-time=3600
user=sail
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
